export const RECONNECT_MAX_RETRIES = 10;
export const RECONNECT_INTERVAL = 1500;
export const WS_NO_STATUS_RECEIVED_CODE = 1005;

export const EVENTS = {
  WS_ADD_MESSAGE: 'WS_ADD_MESSAGE',
  WS_CONNECTED: 'WS_CONNECTED',
  WS_CLOSED: 'WS_CLOSED',
  WS_ERROR: 'WS_ERROR'
};
